# DGB package initializer.

"""DGB package initializer.

Exports package `__version__` when available (generated by setuptools_scm).
"""

try:
    from ._version import version as __version__
except Exception:
    __version__ = "0!unknown"

__all__ = ["__version__"]
